framework:
    router:
        utf8: true

        # https://symfony.com/doc/current/routing.html#generating-urls-in-commands

when@prod:
    framework:
        router:
            strict_requirements: null
