controllers:
    resource: ../src/Controller/
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index

test:
    path: /test
    controller: App\Controller\HomeController::test

admin_index:
    path: /admin
    controller: App\Controller\AdminController::index

admin_create:
    path: /admin/create
    controller: App\Controller\AdminController::create

admin_edit:
    path: /admin/edit/{id}
    controller: App\Controller\AdminController::edit
    requirements:
        id: '\d+'

admin_view:
    path: /admin/view/{id}
    controller: App\Controller\AdminController::view
    requirements:
        id: '\d+'

admin_delete:
    path: /admin/delete/{id}
    controller: App\Controller\AdminController::delete
    methods: [POST]
    requirements:
        id: '\d+'

# Nomenclature routes
nomenclature_index:
    path: /nomenclature
    controller: App\Controller\NomenclatureController::index

nomenclature_characteristic_create:
    path: /nomenclature/characteristic/create
    controller: App\Controller\NomenclatureController::createCharacteristic

nomenclature_characteristic_edit:
    path: /nomenclature/characteristic/edit/{id}
    controller: App\Controller\NomenclatureController::editCharacteristic
    requirements:
        id: '\d+'

nomenclature_characteristic_delete:
    path: /nomenclature/characteristic/delete/{id}
    controller: App\Controller\NomenclatureController::deleteCharacteristic
    methods: [POST]
    requirements:
        id: '\d+'

nomenclature_available_value_create:
    path: /nomenclature/available-value/create
    controller: App\Controller\NomenclatureController::createAvailableValue

nomenclature_available_value_edit:
    path: /nomenclature/available-value/edit/{id}
    controller: App\Controller\NomenclatureController::editAvailableValue
    requirements:
        id: '\d+'

nomenclature_available_value_delete:
    path: /nomenclature/available-value/delete/{id}
    controller: App\Controller\NomenclatureController::deleteAvailableValue
    methods: [POST]
    requirements:
        id: '\d+'

nomenclature_create:
    path: /nomenclature/create
    controller: App\Controller\NomenclatureController::createNomenclature

nomenclature_edit:
    path: /nomenclature/edit/{id}
    controller: App\Controller\NomenclatureController::editNomenclature
    requirements:
        id: '\d+'

nomenclature_delete:
    path: /nomenclature/delete/{id}
    controller: App\Controller\NomenclatureController::deleteNomenclature
    methods: [POST]
    requirements:
        id: '\d+'

api_available_values:
    path: /api/available-values/{characteristicId}
    controller: App\Controller\NomenclatureController::getAvailableValues
    requirements:
        characteristicId: '\d+'
